//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cordova_Builder {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class locale {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal locale() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cordova_Builder.locale", typeof(locale).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대한 현재 스레드의 CurrentUICulture
        ///   속성을 재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   echo Android Platform has been added to your Cordova poject.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string AddAndroidPlatform1 {
            get {
                return ResourceManager.GetString("AddAndroidPlatform1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   echo Can’t add Android Platform.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string AddAndroidPlatform2 {
            get {
                return ResourceManager.GetString("AddAndroidPlatform2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   echo {0} plugin were added to your project.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string AddPlugins1 {
            get {
                return ResourceManager.GetString("AddPlugins1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   echo Can’t add {0} plugin to your project.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string AddPlugins2 {
            get {
                return ResourceManager.GetString("AddPlugins2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Already existed keystore file in your project folder!과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ALREADY_EXISTED_KEYSTORE {
            get {
                return ResourceManager.GetString("ALREADY_EXISTED_KEYSTORE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The Android SDK API Levels does not exist. Please install a new Android API Level using SDK Manager.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ANDROID_API_LEVEL_NOT_FOUND {
            get {
                return ResourceManager.GetString("ANDROID_API_LEVEL_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You are using an alpha version of this program.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CHECK_VERSION_ALPHA {
            get {
                return ResourceManager.GetString("CHECK_VERSION_ALPHA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You are using the latest version of this program.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CHECK_VERSION_LATEST {
            get {
                return ResourceManager.GetString("CHECK_VERSION_LATEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Detected a new version of MV App Builder.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CHECK_VERSION_OLD {
            get {
                return ResourceManager.GetString("CHECK_VERSION_OLD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do you want to update to a new version?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CHECK_VERSION_OLD_ASK {
            get {
                return ResourceManager.GetString("CHECK_VERSION_OLD_ASK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Clear...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CLEAR_BUILD_LOG {
            get {
                return ResourceManager.GetString("CLEAR_BUILD_LOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Start copying game files.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CopyProjectFiles1 {
            get {
                return ResourceManager.GetString("CopyProjectFiles1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   echo Finished copying game files과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CopyProjectFiles2 {
            get {
                return ResourceManager.GetString("CopyProjectFiles2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   echo Cannot be copying game files과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CopyProjectFiles3 {
            get {
                return ResourceManager.GetString("CopyProjectFiles3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The game source directory specified for text box does not exist. Cannot copy game files.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CopyProjectFiles4 {
            get {
                return ResourceManager.GetString("CopyProjectFiles4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   echo Cordova project creation successful.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Create1 {
            get {
                return ResourceManager.GetString("Create1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   echo Cannot Create Project.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Create2 {
            get {
                return ResourceManager.GetString("Create2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   keystore file creation successful.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CreateKeyStore1 {
            get {
                return ResourceManager.GetString("CreateKeyStore1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cannot create the keystore file과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CreateKeyStore2 {
            get {
                return ResourceManager.GetString("CreateKeyStore2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   keystore file creation successful.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CreateKeyStore3 {
            get {
                return ResourceManager.GetString("CreateKeyStore3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Could not create keystore file because it contains invalid parameters.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CreateKeyStore4 {
            get {
                return ResourceManager.GetString("CreateKeyStore4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Could not create keystore file because it contains the empty string.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CreateKeyStore5 {
            get {
                return ResourceManager.GetString("CreateKeyStore5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   -- All the required programs are found!과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cannot find ANDROID_SDK_ROOT or ANDROID_HOME in the Windows Environment Variables과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ENVIRONMENT_VAR_NOT_FOUND {
            get {
                return ResourceManager.GetString("ENVIRONMENT_VAR_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   echo The installation of Cordova encountered an error.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FAIL_INSTALLED_CORDOVA {
            get {
                return ResourceManager.GetString("FAIL_INSTALLED_CORDOVA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Found build.json과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Flush1 {
            get {
                return ResourceManager.GetString("Flush1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   echo build complete.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Flush2 {
            get {
                return ResourceManager.GetString("Flush2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   echo Error occurred while compiling the APK.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Flush3 {
            get {
                return ResourceManager.GetString("Flush3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Found Android SDK from ANDROID_HOME : {0}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FOUND_ANDROID_HOME {
            get {
                return ResourceManager.GetString("FOUND_ANDROID_HOME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Found Android SDK from ANDROID_SDK_ROOT : {0}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FOUND_ANDROID_SDK_ROOT {
            get {
                return ResourceManager.GetString("FOUND_ANDROID_SDK_ROOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   cordova -v과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FOUND_CORDOVA {
            get {
                return ResourceManager.GetString("FOUND_CORDOVA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   java.exe -version 2&gt;&amp;1과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FOUND_JAVA {
            get {
                return ResourceManager.GetString("FOUND_JAVA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   echo Found keytool과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FOUND_KEYTOOL {
            get {
                return ResourceManager.GetString("FOUND_KEYTOOL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Updating Cordova... Please wait, may take up to 1 minutes.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string INSTALLING_CORDOVA {
            get {
                return ResourceManager.GetString("INSTALLING_CORDOVA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Latest stable version is installed.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LATEST_CORDOVA_READY {
            get {
                return ResourceManager.GetString("LATEST_CORDOVA_READY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Modified the index.html과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ModifyHtmlFiles {
            get {
                return ResourceManager.GetString("ModifyHtmlFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Not Network Connected. Version check failed.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NOT_CONNECTED_INTERNET {
            get {
                return ResourceManager.GetString("NOT_CONNECTED_INTERNET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   echo cordova not found과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NOT_FOUND_CORDOVA {
            get {
                return ResourceManager.GetString("NOT_FOUND_CORDOVA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   echo Java not found과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NOT_FOUND_JAVA {
            get {
                return ResourceManager.GetString("NOT_FOUND_JAVA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   echo keytool not found과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NOT_FOUND_KEYTOOL {
            get {
                return ResourceManager.GetString("NOT_FOUND_KEYTOOL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Current Cordova version is out of date.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NOT_LATEST_CORDOV_VER {
            get {
                return ResourceManager.GetString("NOT_LATEST_CORDOV_VER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ---The required tool Not Installed.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NotInstalled {
            get {
                return ResourceManager.GetString("NotInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The Android SDK Not Installed.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NotInstalledAndroidSDK1 {
            get {
                return ResourceManager.GetString("NotInstalledAndroidSDK1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please install Android Studio and Android SDK과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NotInstalledAndroidSDK2 {
            get {
                return ResourceManager.GetString("NotInstalledAndroidSDK2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   https://developer.android.com/studio/?hl=ko과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NotInstalledAndroidSDK3 {
            get {
                return ResourceManager.GetString("NotInstalledAndroidSDK3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please Node.js and Cordova과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NotInstalledCordova1 {
            get {
                return ResourceManager.GetString("NotInstalledCordova1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   https://nodejs.org/ko/download/과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NotInstalledCordova2 {
            get {
                return ResourceManager.GetString("NotInstalledCordova2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   https://www.npmjs.com/package/cordova과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NotInstalledCordova3 {
            get {
                return ResourceManager.GetString("NotInstalledCordova3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please install Java과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NotInstalledJava1 {
            get {
                return ResourceManager.GetString("NotInstalledJava1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   https://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NotInstalledJava2 {
            get {
                return ResourceManager.GetString("NotInstalledJava2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Checking if Cordova is up to date ... (May take up to 5 seconds)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PENDING_CHECK_CORDOVA_VER {
            get {
                return ResourceManager.GetString("PENDING_CHECK_CORDOVA_VER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Checking if program is up to date ... (Please wait 1 seconds)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PENDING_CHECK_PROGRAM_VER {
            get {
                return ResourceManager.GetString("PENDING_CHECK_PROGRAM_VER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   -- Ready과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Ready {
            get {
                return ResourceManager.GetString("Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The latest stable version is v{0}, you need to update Cordova과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string REQUEST_NPM_INSTALL {
            get {
                return ResourceManager.GetString("REQUEST_NPM_INSTALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do you want to update the Cordova?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string REQUEST_NPM_INSTALL_ASK {
            get {
                return ResourceManager.GetString("REQUEST_NPM_INSTALL_ASK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   echo ...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Requirements1 {
            get {
                return ResourceManager.GetString("Requirements1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   echo ...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Requirements2 {
            get {
                return ResourceManager.GetString("Requirements2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save Log과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SAVE_BUILD_LOG {
            get {
                return ResourceManager.GetString("SAVE_BUILD_LOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   echo Job completed!과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SUCCESS_INSTALLED_CORDOVA {
            get {
                return ResourceManager.GetString("SUCCESS_INSTALLED_CORDOVA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You have successfully downloaded the installer.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SUCCESSED_SETUP_FILE {
            get {
                return ResourceManager.GetString("SUCCESSED_SETUP_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Modified the config.xml과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string WriteConfig {
            get {
                return ResourceManager.GetString("WriteConfig", resourceCulture);
            }
        }
    }
}
