//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cordova_Builder {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class locale {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal locale() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cordova_Builder.locale", typeof(locale).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대한 현재 스레드의 CurrentUICulture
        ///   속성을 재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   echo 안드로이드 프로젝트가 추가되었습니다과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string AddAndroidPlatform1 {
            get {
                return ResourceManager.GetString("AddAndroidPlatform1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   echo 안드로이드 프로젝트 추가에 실패하였습니다과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string AddAndroidPlatform2 {
            get {
                return ResourceManager.GetString("AddAndroidPlatform2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   echo {0} 플러그인이 추가되었습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string AddPlugins1 {
            get {
                return ResourceManager.GetString("AddPlugins1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   echo {0} 플러그인을 추가하는 데 실패하였습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string AddPlugins2 {
            get {
                return ResourceManager.GetString("AddPlugins2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   게임 폴더 복사를 시작합니다 [robocopy 사용]과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CopyProjectFiles1 {
            get {
                return ResourceManager.GetString("CopyProjectFiles1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   echo 폴더를 www 폴더로 복사하였습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CopyProjectFiles2 {
            get {
                return ResourceManager.GetString("CopyProjectFiles2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   echo 폴더 복사에 실패하였습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CopyProjectFiles3 {
            get {
                return ResourceManager.GetString("CopyProjectFiles3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   복사 할 폴더가 존재하지 않아 파일을 복사할 수 없습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CopyProjectFiles4 {
            get {
                return ResourceManager.GetString("CopyProjectFiles4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   echo 프로젝트를 생성하였습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Create1 {
            get {
                return ResourceManager.GetString("Create1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   echo 프로젝트 생성에 실패하였습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Create2 {
            get {
                return ResourceManager.GetString("Create2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   키스토어 파일이 생성되었습니다과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CreateKeyStore1 {
            get {
                return ResourceManager.GetString("CreateKeyStore1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   키스토어 파일 생성에 실패하였습니다과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CreateKeyStore2 {
            get {
                return ResourceManager.GetString("CreateKeyStore2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   키스토어 파일이 생성되었습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CreateKeyStore3 {
            get {
                return ResourceManager.GetString("CreateKeyStore3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   이미 파일이 존재하거나. 유효하지 않은 매개변수를 입력하였습니다. 키스토어 파일 생성에 실패하였습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CreateKeyStore4 {
            get {
                return ResourceManager.GetString("CreateKeyStore4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   비어있는 칸이 있어서 키스토어 파일을 생성할 수 없습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CreateKeyStore5 {
            get {
                return ResourceManager.GetString("CreateKeyStore5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   --- 필요한 모든 프로그램이 설치되어있습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   build.json 파일을 찾았습니다과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Flush1 {
            get {
                return ResourceManager.GetString("Flush1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   echo 빌드가 완료되었습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Flush2 {
            get {
                return ResourceManager.GetString("Flush2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   echo 빌드 중에 오류가 발생하였습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Flush3 {
            get {
                return ResourceManager.GetString("Flush3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   안드로이드 SDK / ANDROID_HOME를 찾았습니다 : {0}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FOUND_ANDROID_HOME {
            get {
                return ResourceManager.GetString("FOUND_ANDROID_HOME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   안드로이드 SDK / ANDROID_SDK_ROOT를 찾았습니다 : {0}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FOUND_ANDROID_SDK_ROOT {
            get {
                return ResourceManager.GetString("FOUND_ANDROID_SDK_ROOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   cordova -v과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FOUND_CORDOVA {
            get {
                return ResourceManager.GetString("FOUND_CORDOVA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   @&quot;java.exe -version 2&gt;&amp;1과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FOUND_JAVA {
            get {
                return ResourceManager.GetString("FOUND_JAVA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   echo -- keytool을 찾았습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FOUND_KEYTOOL {
            get {
                return ResourceManager.GetString("FOUND_KEYTOOL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   index.html 파일을 수정하였습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ModifyHtmlFiles {
            get {
                return ResourceManager.GetString("ModifyHtmlFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   echo -- cordova를 찾지 못했습니다과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NOT_FOUND_CORDOVA {
            get {
                return ResourceManager.GetString("NOT_FOUND_CORDOVA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   echo -- 자바를 찾지 못했습니다과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NOT_FOUND_JAVA {
            get {
                return ResourceManager.GetString("NOT_FOUND_JAVA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   echo -- keytool을 찾지 못했습니다과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NOT_FOUND_KEYTOOL {
            get {
                return ResourceManager.GetString("NOT_FOUND_KEYTOOL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   --- [ERROR] 필요한 프로그램이 설치되어있지 않습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NotInstalled {
            get {
                return ResourceManager.GetString("NotInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   안드로이드 SDK가 설치되어있지 않습니다과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NotInstalledAndroidSDK1 {
            get {
                return ResourceManager.GetString("NotInstalledAndroidSDK1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   안드로이드 SDK를 설치해주십시오.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NotInstalledAndroidSDK2 {
            get {
                return ResourceManager.GetString("NotInstalledAndroidSDK2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   https://developer.android.com/studio/?hl=ko과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NotInstalledAndroidSDK3 {
            get {
                return ResourceManager.GetString("NotInstalledAndroidSDK3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Node.js와 cordova를 설치해야 합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NotInstalledCordova1 {
            get {
                return ResourceManager.GetString("NotInstalledCordova1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   https://nodejs.org/ko/download/과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NotInstalledCordova2 {
            get {
                return ResourceManager.GetString("NotInstalledCordova2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   https://www.npmjs.com/package/cordova과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NotInstalledCordova3 {
            get {
                return ResourceManager.GetString("NotInstalledCordova3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   자바를 설치해주세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NotInstalledJava1 {
            get {
                return ResourceManager.GetString("NotInstalledJava1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   https://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NotInstalledJava2 {
            get {
                return ResourceManager.GetString("NotInstalledJava2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   --- 준비 ---과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Ready {
            get {
                return ResourceManager.GetString("Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   echo ...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Requirements1 {
            get {
                return ResourceManager.GetString("Requirements1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   echo ...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Requirements2 {
            get {
                return ResourceManager.GetString("Requirements2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   config.xml 파일을 수정하였습니다과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string WriteConfig {
            get {
                return ResourceManager.GetString("WriteConfig", resourceCulture);
            }
        }
    }
}
